steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/weevre/github_jameone_tiicot-api/ui:$SHORT_SHA',
      '-t', 'gcr.io/weevre/github_jameone_tiicot-api/ui:latest', '.']
    dir: './'
images: ['gcr.io/weevre/github_jameone_tiicot-api/api']
